site_name: Deescovery
repo_url: https://github.com/imankulov/deescovery
repo_name: deescovery

plugins:
  - search
  - include-markdown
  - mkdocstrings:
      watch:
        - deescovery

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - Home: index.md
  - flask.md
  - anything_else.md
  - API: api.md


theme:
  name: material
  language: en
