site_name: Roman Discovery
repo_url: https://github.com/imankulov/roman_discovery
repo_name: roman_discovery

plugins:
  - search
  - mkdocstrings:
      watch:
        - roman_discovery

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - Home: index.md
  - API: api.md


theme:
  name: material
  language: en
