name: dev workflow

# Controls when the action will run.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    strategy:
      matrix:
        python-versions: [3.7, 3.8, 3.9]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Install dependencies
        run: |
          set -ex
          curl -O -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py
          python get-poetry.py --yes
          rm -f get-poetry.py
          $HOME/.poetry/bin/poetry install

      - name: Install tox
        run: |
          $HOME/.poetry/bin/poetry add tox tox-gh-actions

      - name: Test with tox
        run:
          $HOME/.poetry/bin/poetry tox
